### ISSUE TITLE
What exactly is the api-user?

### ISSUE THREAD

**Issue by zendevil** [camdez/sendgrid#1]
I'm unable to send an email. I'm getting the following:

```
=> (sendgrid/profile sg-config)
Execution error (ExceptionInfo) at sendgrid.request/handle-api-errors (request.clj:31).
Permission denied, wrong credentials

```

I'm putting the api-user as the email that I signed up with, and the api key as the api key that I created on SendGrid. Why am I seeing this error then?

**Comment by camdez** [comment]
Hi @zendevil, sorry for the super late response here.

The library was using an old form of authentication where you had to provide your username.  It has now been updated to take a (modern-style) API key.
